- name: Prepare the new server for Ansible
# =========================================
  hosts: databox-host
  strategy: debug
  gather_facts: no

  remote_user: root
  become: true

  tasks:
    - name: Install Python using a raw SSH command to enable the execution of Ansible modules
      raw: apt update && apt install python -y
      args:
        executable: /bin/bash

- name: Configure the Server and install required software
# ========================================================
  hosts: databox-host

  remote_user: root
  become: true

  roles:
    - common
    - openconnect
    - l2tp-ipsec
    - openvpn
    - shadowsocks
    - ssh
    - tinyproxy
    - sslh
    - monit
    - ufw
    - streisand-gateway
